### Cadastrar uma nova empresa
POST http://localhost:8080/empresa/cadastrar
Content-Type: application/json

{
  "id": 1,
  "razaoSocial": "Empresa 1",
  "nomeFantasia": "Empresa 1",
  "cadastro": "2025-01-01",
  "endereco": {
    "id": 1,
    "estado": "SP",
    "cidade": "São Paulo",
    "bairro": "Jardim Paulista",
    "rua": "Rua das Flores",
    "numero": "123",
    "codigoPostal": "04101-300",
    "informacoesAdicionais": "Apto 101"
  },
  "telefones": [
    {
      "id": 1,
      "numero": "1234567898",
    }
  ]
}

### Obter todos os documentos
GET http://localhost:8080/empresa/listar

### Obter um documento específico
GET http://localhost:8080/empresa/1

### Atualizar um documento
PUT http://localhost:8080/empresa/atualizar
Content-Type: application/json

{
  "id": 1,
  "razaoSocial": "razaoSocial 321"
}

### Excluir um documento
DELETE http://localhost:8080/empresa/excluir
Content-Type: application/json

{
  "id": 1
}
