### Create client
POST http://localhost:8080/usuario/cadastro
Content-Type: application/json

{
  "id": 2,
  "nome": "João da Silva",
  "nomeSocial": "João da Silva",
  "empresa": {
    "id": 1,
    "razaoSocial": "Empresa 1",
    "cadastro": "2025-01-01"

  },
  "perfil": "FUNCIONARIO",
  "dataNascimento": "1990-01-01",
  "dataCadastro": "2000-01-01",
  "documentos": [
    {
      "id": 2,
      "tipo": "CPF",
      "dataEmissao": "2020-01-01",
      "numero": "0124567890"
    }
  ],
  "endereco": {
    "id": 2,
    "estado": "SP",
    "cidade": "São Paulo",
    "bairro": "Jardim Paulista",
    "rua": "Rua das Flores",
    "numero": "123",
    "codigoPostal": "04101-300",
    "informacoesAdicionais": "Apto 101"
  },
  "telefones": [
    {
      "id": 2,
      "ddd": "11",
      "numero": "99999-9999"
    }
  ],
  "credencialCodigoBarra":{ 
    "codigo": 1,
    "criacao":"2020-01-01"
  }
}

### Obter todos os clientes
GET http://localhost:8080/usuario/listar

### Get user
GET http://localhost:8080/usuario/1

### Update user
PUT http://localhost:8080/usuario/atualizar/1
Content-Type: application/json

{
  "id": 1,
  "nome": "Rain dos Santos",
  "nomeSocial": "Rainizinho",
  "dataNascimento": "1990-01-01",
  "dataCadastro": "2025-01-01",
  "documentos": [
    {
      "id": 1,
      "tipo": "CPF",
      "numero": "1234567890",
      "dataEmissao": "2020-01-01"
    }
  ],
  "endereco": {
    "id": 1,
    "estado": "RJ",
    "cidade": "São Paulo",
    "bairro": "Jardim Paulista",
    "rua": "Rua das Flores",
    "numero": "123",
    "codigoPostal": "04101-300",
    "informacoesAdicionais": "Apto 101"
  },
  "telefones": [
    {
      "id": 1,
      "ddd": "11",
      "numero": "99999-9999"
    }
  ]
}

### Delete
DELETE http://localhost:8080/cliente/excluir
Content-Type: application/json

{
  "id": 1,
  "nome": "Raim dos Santos",
  "nomeSocial": "Raimizinho",
  "dataNascimento": "1990-01-01",
  "dataCadastro": "2025-01-01",
  "documentos": [
    {
      "id": 1,
      "tipo": "CPF",
      "numero": "1234567890"
    }
  ],
  "cliente": {
    "id": 1,
    "estado": "SP",
    "cidade": "São Paulo",
    "bairro": "Jardim Paulista",
    "rua": "Rua das Flores",
    "numero": "123",
    "codigoPostal": "04101-300",
    "informacoesAdicionais": "Apto 101"
  },
  "telefones": [
    {
      "id": 1,
      "ddd": "11",
      "numero": "99999-9999"
    }
  ]
}
