### Cadastrar uma nova venda

POST http://localhost:8080/venda/1/cadastro HTTP/1.1
Authorization: Bearer {{JWT}}
Content-Type: application/json

{
  "id": 1,
  "cadastro": "2025-01-01",
  "identificacao": "1234567890",
  "cliente": {
    "id": 2
  },
  "funcionario": {
    "id": 1
  },
  "mercadorias": [
    {
      "id": 1
    }
  ],
  "servicos": [
    {
      "id": 1
    }
  ]
}

### Obter todas as vendas

GET http://localhost:8080/venda/1/listar HTTP/1.1
Authorization: Bearer {{JWT}}

### Obter uma venda específica

GET http://localhost:8080/venda/1 HTTP/1.1

### Atualizar uma venda

PUT http://localhost:8080/venda/atualizar/1 HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "cadastro": "2025-01-01",
  "identificacao": "3334567890",
  "cliente": {
    "id": 1
  },
  "funcionario": {
    "id": 1
  },
  "mercadorias": [
    {
      "id": 1
    }
  ],
  "servicos": [
    {
      "id": 1
    }
  ]
}

### Excluir uma venda

DELETE http://localhost:8080/venda/excluir HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "cadastro": "2025-01-01",
  "identificacao": "1234567890",
  "cliente": {
    "id": 1
  },
  "funcionario": {
    "id": 1
  },
  "mercadorias": [
    {
      "id": 1
    }
  ],
  "servicos": [
    {
      "id": 1
    }
  ]
}
